[tool.black]
line-length = 99
target-version = ["py38"]
exclude = '''
/(
    \.eggs
  | \.git
  | \.mypy_cache
  | \.vscode
  | env
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
src_paths = ["optuna_distributed", "tests", "examples"]
line_length = 99
lines_after_imports = 2
force_single_line = "True"
force_sort_within_sections = "True"
order_by_type = "False"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.mypy]
warn_unused_configs = "True"
disallow_untyped_calls = "True"
disallow_untyped_defs = "True"
disallow_incomplete_defs = "True"
check_untyped_defs = "True"
no_implicit_optional = "True"
warn_redundant_casts = "True"
strict_equality = "True"
strict_concatenate = "True"
